#!/usr/bin/env bash

set -o errexit

export WORKDIR=$(dirname "$(readlink -f "$0")")
export USER_ID=$(id -u)

pushd "$WORKDIR" >/dev/null

COMPOSE_FILE="$1/docker-compose.yml"

if ! [ -f "$COMPOSE_FILE" ]; then
  SCRIPT_NAME=$(basename "$0")
  echo "$1 is not a service directory"
  echo "usage: $SCRIPT_NAME <service_dir> <...docker compose arguments>"
  exit 1
fi

docker compose -f "$COMPOSE_FILE" "${@:2}"

popd >/dev/null
