services:
  gateway:
    image: nginx:1.27.5-alpine
    container_name: gateway
    restart: unless-stopped
    volumes:
      - './log/nginx:/var/log/nginx'
      - './config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './config/nginx/conf.d:/etc/nginx/conf.d:ro'
      - './certs:/etc/ssl:ro'
    ports:
      # HTTP interfaces
      - '80:80'
      - '443:443'
      # Gitea SSH
      - '2222:2222'
      # Dokku SSH
      - '3022:3022'
    depends_on:
      - gitea
      - dokku
      - grafana

  gitea:
    image: gitea/gitea:1.24.0-rootless
    container_name: gitea
    restart: unless-stopped
    environment:
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: gitea-db:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: b7ysaoyH
    volumes:
      - './data/gitea:/var/lib/gitea'
      - './config/gitea:/etc/gitea'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    depends_on:
      - gitea-db

  gitea-act-runner:
    image: gitea/act_runner:nightly
    container_name: gitea-act-runner
    restart: unless-stopped
    environment:
      GITEA_INSTANCE_URL: http://gitea:3000
      GITEA_RUNNER_REGISTRATION_TOKEN: '#SECRET'
      GITEA_RUNNER_NAME: 'Gitea Runner'
    volumes:
      - './data/gitea-act-runner:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - gitea
      - gitea-db

  gitea-db:
    image: postgres:17.5-alpine
    container_name: gitea-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: b7ysaoyH
    volumes:
      - './data/gitea-db:/var/lib/postgresql/data'

  dokku:
    image: dokku/dokku:0.36.7
    container_name: dokku
    restart: unless-stopped
    volumes:
      - '/var/lib/dokku:/mnt/dokku'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      DOKKU_HOSTNAME: dokku.raspberry.lan
      DOKKU_HOST_ROOT: /var/lib/dokku/home/dokku
      DOKKU_LIB_HOST_ROOT: /var/lib/dokku/var/lib/dokku

  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    restart: unless-stopped
    volumes:
      - './data/grafana:/var/lib/grafana'

