services:
  proxy:
    image: nginx:1.27.5-alpine
    container_name: proxy
    restart: always
    volumes:
      - ./~conf/nginx:/app/etc/nginx:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gitea

  gitea:
    image: docker.gitea.com/gitea:1.23.8
    container_name: gitea
    restart: always
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea-db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - gitea-db

  gitea-db:
    image: docker.io/library/mysql:8
    container_name: gitea-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - ./mysql:/var/lib/mysql
