#!/usr/bin/env bash

set -o errexit

mkdir -p ./certs

openssl req -x509 -nodes -days 365 \
  -newkey rsa:2048 \
  -keyout ./certs/localhost.key \
  -out ./certs/localhost.crt

echo "Certificates generated OK"
