services:
  gateway:
    image: nginx:1.27.5-alpine
    container_name: gateway
    restart: always
    user: "$USER_ID"
    volumes:
      - './log:/var/log/nginx'
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - './conf.d:/etc/nginx/conf.d:ro'
      - './certs:/etc/ssl:ro'
    ports:
      # HTTP interfaces
      - '80:80'
      - '443:443'
      # Gitea SSH
      - '2222:2222'
      # Pihole DNS
      - '53:53/tcp'
      - '53:53/udp'
    networks:
      - raspberry

networks:
  raspberry:
    external: true
