services:
  gitea:
    image: gitea/gitea:1.24.0-rootless
    container_name: gitea
    restart: always
    user: "$USER_ID"
    environment:
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: gitea-db:3306
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: b7ysaoyH
    volumes:
      - './data/gitea:/var/lib/gitea'
      - './config:/etc/gitea'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    networks:
      - raspberry
      - internal
    depends_on:
      - gitea-db

  gitea-act-runner:
    image: gitea/act_runner:nightly
    container_name: gitea-act-runner
    restart: always
    user: "$USER_ID"
    environment:
      GITEA_INSTANCE_URL: http://gitea:3000
      GITEA_RUNNER_REGISTRATION_TOKEN: '#SECRET'
      GITEA_RUNNER_NAME: 'Gitea Runner'
    volumes:
      - './data/gitea-act-runner:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - internal
    depends_on:
      - gitea
      - gitea-db

  gitea-db:
    image: mysql:8.0
    container_name: gitea-db
    restart: always
    user: "$USER_ID"
    environment:
      MYSQL_ROOT_PASSWORD: svxTbcF3
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: b7ysaoyH
    volumes:
      - './data/gitea-db:/var/lib/mysql'
    networks:
      - internal

networks:
  internal:
  raspberry:
    external: true
