services:
  pihole:
    image: pihole/pihole:2025.06.1
    container_name: pihole
    restart: unless-stopped
    user: "$USER_ID"
    environment:
      TZ: 'Europe/Moscow'
      FTLCONF_webserver_api_password: 'pV4Num'
    volumes:
      - './data:/etc/pihole'
    networks:
      - raspberry

networks:
  raspberry:
    external: true
