services:
  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    restart: unless-stopped
    user: "$USER_ID"
    volumes:
      - './data:/var/lib/grafana'
    networks:
      - raspberry

networks:
  raspberry:
    external: true
