name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:

  release:
    name: Automatic release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create the release
        uses: softprops/action-gh-release@v2
